[build]
  command = "pip install -r requirements.txt"
  publish = "public"

[functions]
  directory = "functions"

[functions.python]
  runtime = "python3.8"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
