[build]
  command = "pip install -r requirements.txt"
  publish = "public" # Changed to a dedicated (empty) folder

[functions]
  directory = "functions"

[functions.python]
  # Explicitly tell Netlify to use Python
  runtime = "python3.8"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
